### ISSUE TITLE
Wrong source map is generated

### ISSUE THREAD

**Issue by sospedra** [facebook/metro#148]
We came from this discussion on `react-native` repo where @hramos recommend us to move the issue here: https://github.com/facebook/react-native/issues/6946

You can find all the detailed information in there. Tho, to summarize: the packager generates the sourcemap with wrong lines more times that I'd like to recon.

Problem is still raising in latests versions. Thank you :)

**Comment by HazAT** [comment]
I can confirm, tried it with the latest version and the error is still in there.
I am not really sure though I have a repro case locally but haven't had enough time to dive through the whole codebase to create a minimal independent repro case. (The one I have right now requires way to much setup).

I suspect the issue lies somewhere when metro is stitching together all sources/sources maps that come from uglify.

**Comment by rafeca** [comment]
Thanks for reporting! A minimal repro scenario would indeed help us a lot reproducing and fixing the issue

**Comment by xutm** [comment]
why close the issue?

**Comment by anandprabhu** [comment]
@rafeca Here is a simple test repository to reproduce the issue along with the steps i have followed.
https://github.com/anandprabhu/HelloRN

**Comment by rafeca** [comment]
Thanks @anandprabhu! I'm currently on PTO, I'll take a look at this next week when I'm back to the office

**Comment by rafeca** [comment]
Hey @anandprabhu , I've spent some time debugging the issue. First of all, thanks for the test repository and the repro instructions, it makes it so much easier to debug these kind of issues 👍 

After reproducing it, I think that the issue comes from React Native itself (not sure if it's from some native layer of from the JS interpreter).

What makes me think that is that the first line that gets reported by `pidcat` is already wrong (before even being symbolicated using the sourcemaps):

```
onPress@303:987
...
```

To check that, you can open the actual minified bundle from `android/app/build/intermediates/assets/release/index.android.bundle` and go to line 303, column 987 and you'll see that it does not point indeed to the place where the error is thrown.

From this point, metro sourcemaps are working fine, since they translate that position to its corresponding source position.

I think that with this additional information, the discussion can be moved back to https://github.com/facebook/react-native/issues/6946

**Comment by rafeca** [comment]
Closing this issue

**Comment by rafeca** [comment]
Just found out that this issue is actually caused by metro! sorry about that, a fix is coming really soon 😃

**Comment by jshearer** [comment]
And updates on this? I'm having trouble with sourcemap lines being all over the place, unable to set breakpoints, without using 'debugger', etc.

**Comment by rafeca** [comment]
@jshearer the fix was released with metro v0.37.2, and should be available on RN 0.56.0

**Comment by fzyzcjy** [comment]
@rafeca I am using RN 0.55.4. Is it possible to use the version with that fix? Thanks!

**Comment by sospedra** [comment]
Wohooo! 🎊

**Comment by AndresCardonaDev** [comment]
Hi, im on react-native 0.57.1 The problem is still there, even debugger; statements makes chrome stop at a shifted place, it is impossible to debug as it is, there is some cache to clean?

**Comment by robozb** [comment]
The debugger is usless on this way, the breakpoints is shifted:

https://github.com/facebook/metro/assets/8656998/e0f74136-0af1-4b34-9e01-ff0c98c04a69

```
...
"dependencies": {
  "expo": "~49.0.8",
  "expo-status-bar": "~1.6.0",
  "react": "18.2.0",
  "react-native": "0.72.4"
},
"devDependencies": {
  "@babel/core": "^7.20.0"
},
...
```
